#!/usr/bin/env python3
"""Generate INDEX.md from problem frontmatter. Do not edit INDEX.md by hand."""
import io
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
PROBLEMS = ROOT / "problems"
AXES = ("geometry", "selection", "formalization", "epistemic", "experimental")
STATUSES = ("active", "open", "dormant", "closed")
REQUIRED = ("title", "axis", "status", "opened", "updated")


def parse_frontmatter(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path.name}: missing frontmatter")
    meta = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
    return meta


def validate(name, meta):
    errors = [f"{name}: missing field '{k}'" for k in REQUIRED if k not in meta]
    if meta.get("axis") and meta["axis"] not in AXES:
        errors.append(f"{name}: axis '{meta['axis']}' not in {AXES}")
    if meta.get("status") and meta["status"] not in STATUSES:
        errors.append(f"{name}: status '{meta['status']}' not in {STATUSES}")
    return errors


def main():
    problems, errors = [], []
    for path in sorted(PROBLEMS.glob("*.md")):
        meta = parse_frontmatter(path)
        errors.extend(validate(path.name, meta))
        meta["file"] = f"problems/{path.name}"
        problems.append(meta)
    if errors:
        print("\n".join(errors))
        sys.exit(1)

    counts = {s: sum(1 for p in problems if p["status"] == s) for s in STATUSES}
    out = ["# Problem index", "",
           f"{len(problems)} problems ("
           + ", ".join(f"{counts[s]} {s}" for s in STATUSES if counts[s]) + "). "
           "Generated by `scripts/build_index.py`; do not edit by hand.", ""]

    for axis in AXES:
        group = [p for p in problems if p["axis"] == axis]
        if not group:
            continue
        out.append(f"\n## {axis.capitalize()} ({len(group)})\n")
        for p in sorted(group, key=lambda x: (STATUSES.index(x["status"]), x["title"].lower())):
            out.append(f"- [{p['title']}]({p['file']}) · **{p['status']}** · updated {p['updated']}")

    (ROOT / "INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"INDEX.md written: {len(problems)} problems, "
          + ", ".join(f"{counts[s]} {s}" for s in STATUSES if counts[s]))


if __name__ == "__main__":
    main()
